// Generated by CoffeeScript 1.4.0
(function() {
  var common;

  common = {
    EventEmitter: require('events').EventEmitter,
    fs: require('fs'),
    net: require('net'),
    Q: require('q'),
    tls: require('tls'),
    _: require('underscore')
  };

  module.exports = common;

}).call(this);
