// Generated by CoffeeScript 1.4.0
(function() {
  var common;

  common = {
    EventEmitter: require('events').EventEmitter,
    fs: require('fs'),
    net: require('net'),
    Q: require('q'),
    tls: require('tls'),
    _: require('underscore')
  };

  common.defer = function(fn) {
    var d;
    d = common.Q.defer();
    fn(d.resolve, d.reject);
    return d.promise;
  };

  module.exports = common;

}).call(this);
